I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1390, in script
    "Nah":
  File "game/script.rpy", line 1390, in <module>
    "Nah":
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1390, in script
    "Nah":
  File "C:\Users\Jose\Downloads\renpy-6.17.7-sdk\renpy\ast.py", line 1225, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\Jose\Downloads\renpy-6.17.7-sdk\renpy\python.py", line 1416, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 1390, in <module>
    "Nah":
NameError: name 'flash' is not defined

Windows-post2008Server-6.2.9200
Ren'Py 6.18.2.729
Doctor-Sim 0.01:3
